#!/usr/bin/with-contenv bashio
# shellcheck shell=bash

conf_directory="/config/rtl_433"

# Base port for the first radio's HTTP server. Each additional radio is assigned
# the next sequential port. The Home Assistant integration connects to
# ws://<host>:<port>/ws.
BASE_PORT=8433

# Maximum number of radios (and therefore HTTP ports) supported. Templates
# beyond this count are skipped.
MAX_RADIOS=10

if [ ! -d "$conf_directory" ]
then
    mkdir -p "$conf_directory"
fi

# Create a reasonable default configuration in /config/rtl_433.
if [ ! "$(ls -A "$conf_directory")" ]
then
    cat > "$conf_directory"/rtl_433.conf.template <<EOD
# This template configures rtl_433 to expose its decoded events over an HTTP
# server. The Home Assistant integration connects to that server (ws://host:port/ws)
# to receive device data. Each radio runs its own rtl_433 process with its own
# HTTP port.
#
# Create multiple files ending in '.conf.template' to manage multiple rtl_433
# radios. Each template MUST set a distinct 'device' so radios can be told apart,
# for example 'device :SERIAL' or a SoapySDR device string. The 'device' line
# must appear before any output lines.
#
# Radios are sorted by their 'device' value and assigned a stable HTTP port
# starting at ${BASE_PORT} (so the first radio binds ${BASE_PORT}, the second
# ${BASE_PORT}+1, and so on). The \${port} placeholder below is filled in at
# render time with this radio's assigned port.
# https://github.com/merbanan/rtl_433/blob/master/conf/rtl_433.example.conf

device 0

output http://0.0.0.0:\${port}
report_meta time:iso:usec:tz

# Uncomment the following line to also enable the default "table" output to the
# addon logs.
# output kv

# Disable TPMS sensors by default. These can cause an overwhelming number of
# devices and entities to show up in Home Assistant.
# This list is generated by running:
# rtl_433 -R help 2>&1 | grep -i tpms | sd '.*\[(\d+)\].*' 'protocol -$1'
#    [59]  Steelmate TPMS
#    [60]  Schrader TPMS
#    [82]  Citroen TPMS
#    [88]  Toyota TPMS
#    [89]  Ford TPMS
#    [90]  Renault TPMS
#    [95]  Schrader TPMS EG53MA4, PA66GF35
#    [110]  PMV-107J (Toyota) TPMS
#    [123]* Jansite TPMS Model TY02S
#    [140]  Elantra2012 TPMS
#    [156]  Abarth 124 Spider TPMS
#    [168]  Schrader TPMS SMD3MA4 (Subaru)
#    [180]  Jansite TPMS Model Solar
#    [186]  Hyundai TPMS (VDO)
#    [201]  Unbranded SolarTPMS for trucks
#    [203]  Porsche Boxster/Cayman TPMS
protocol -59
protocol -60
protocol -82
protocol -88
protocol -89
protocol -90
protocol -95
protocol -110
protocol -123
protocol -140
protocol -156
protocol -168
protocol -180
protocol -186
protocol -201
protocol -203
EOD
fi

# Remove all rendered configuration files.
rm -f "$conf_directory"/*.conf

# Build the list of templates, pairing each with its 'device' value so we can
# sort deterministically and assign stable ports.
templates_by_device=()
for template in "$conf_directory"/*.conf.template
do
    # Skip the glob literal if no templates exist.
    [ -e "$template" ] || continue

    # Extract the device value from the first 'device ' line in the template.
    device=$(grep -m1 '^[[:space:]]*device[[:space:]]' "$template" | sed -E 's/^[[:space:]]*device[[:space:]]+//')
    if [ -z "$device" ]
    then
        bashio::log.warning "Template $template has no 'device' line; defaulting to an empty device value."
    fi

    # Prefix with the device value (tab-separated) so we can sort on it.
    templates_by_device+=("${device}"$'\t'"${template}")
done

# Sort templates by device value for a deterministic, stable ordering.
mapfile -t sorted_templates < <(printf '%s\n' "${templates_by_device[@]}" | sort)

# Parallel arrays describing each launched radio. These are populated during port
# assignment/launch and are the integration point for a later discovery task,
# which iterates them to publish Home Assistant discovery.
# shellcheck disable=SC2034  # consumed by the discovery step (see task 3)
radio_devices=()
# shellcheck disable=SC2034  # consumed by the discovery step (see task 3)
radio_ports=()
# shellcheck disable=SC2034  # consumed by the discovery step (see task 3)
radio_tags=()

rtl_433_pids=()
index=0
for entry in "${sorted_templates[@]}"
do
    # Split the "device<TAB>template" entry back into its parts.
    device="${entry%%$'\t'*}"
    template="${entry#*$'\t'}"

    if [ "$index" -ge "$MAX_RADIOS" ]
    then
        bashio::log.warning "More than ${MAX_RADIOS} radio templates found; the maximum supported is ${MAX_RADIOS}. Skipping $template."
        index=$((index + 1))
        continue
    fi

    # Assign a stable port based on the sorted position of this radio.
    # 'port' is referenced by the heredoc template via ${port}.
    # shellcheck disable=SC2034
    port=$((BASE_PORT + index))

    # Remove '.template' from the file name.
    live=$(basename "$template" .template)
    tag=$(basename "$live" .conf)

    radio_devices+=("$device")
    radio_ports+=("$port")
    radio_tags+=("$tag")

    bashio::log.info "Radio '${device:-<none>}' (template $tag) assigned HTTP port ${port}."

    # By sourcing the template, we can substitute any environment variable in
    # the template. In fact, enterprising users could write _any_ valid bash
    # to create the final configuration file. To simplify template creation,
    # we wrap the needed redirections into a temporary file.
    {
        echo "cat <<EOD > $live"
        cat "$template"
        # Ensure a newline exists in case the template doesn't have one at the end
        # of its file.
        echo
        echo EOD
    } > /tmp/rtl_433_heredoc

    # shellcheck source=/dev/null
    source /tmp/rtl_433_heredoc

    echo "Starting rtl_433 with $live..."
    rtl_433 -c "$live" > >(sed -u "s/^/[$tag] /") 2> >(>&2 sed -u "s/^/[$tag] /")&
    rtl_433_pids+=($!)

    index=$((index + 1))
done

wait -n "${rtl_433_pids[@]}"
