name: Lint Dockerfiles

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  hadolint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Lint rtl_433 Dockerfile
        id: lint-rtl_433
        uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 # v3.3.0
        continue-on-error: true
        with:
          dockerfile: rtl_433/Dockerfile
      - name: Check lint results
        if: steps.lint-rtl_433.outcome == 'failure'
        run: exit 1
