name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  bats:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install bats
        run: sudo apt-get update && sudo apt-get install -y bats
      - name: Run BATS tests
        run: bats -r tests/
