name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  bats:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Install bats
        run: sudo apt-get update && sudo apt-get install -y bats
      - name: Run BATS tests
        run: bats -r tests/
